# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:04:23+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity
from fastapi import Path

from models import (
    APIClassifiersStatusOut,
    APIClassifierTaxonomyOut,
    APIKeyOut,
    APIPeriodUsageOut,
    APIServicesOut,
    APIUsageAggregatedOut,
    APIUsageHistoryOut,
    BatchCorridorIn,
    BatchCorridorOut,
    BatchFirstLastNameDiasporaedOut,
    BatchFirstLastNameGenderedOut,
    BatchFirstLastNameGenderIn,
    BatchFirstLastNameGeoIn,
    BatchFirstLastNameGeoSubclassificationOut,
    BatchFirstLastNameGeoZippedIn,
    BatchFirstLastNameIn,
    BatchFirstLastNameOriginedOut,
    BatchFirstLastNamePhoneCodedOut,
    BatchFirstLastNamePhoneNumberGeoIn,
    BatchFirstLastNamePhoneNumberIn,
    BatchFirstLastNameUSRaceEthnicityOut,
    BatchMatchPersonalFirstLastNameIn,
    BatchNameGeoIn,
    BatchNameIn,
    BatchNameMatchCandidatesOut,
    BatchNameMatchedOut,
    BatchPersonalNameCastegroupOut,
    BatchPersonalNameGenderedOut,
    BatchPersonalNameGeoIn,
    BatchPersonalNameGeoOut,
    BatchPersonalNameGeoSubdivisionIn,
    BatchPersonalNameIn,
    BatchPersonalNameParsedOut,
    BatchPersonalNameReligionedOut,
    BatchPersonalNameSubdivisionIn,
    BatchProperNounCategorizedOut,
    CorridorOut,
    FeedbackLoopOut,
    FirstLastNameDiasporaedOut,
    FirstLastNameGenderedOut,
    FirstLastNameGeoSubclassificationOut,
    FirstLastNameOriginedOut,
    FirstLastNamePhoneCodedOut,
    FirstLastNameUSRaceEthnicityOut,
    NameMatchCandidatesOut,
    NameMatchedOut,
    PersonalNameCastegroupOut,
    PersonalNameGenderedOut,
    PersonalNameGeoOut,
    PersonalNameParsedOut,
    PersonalNameReligionedOut,
    ProperNounCategorizedOut,
    RegionOut,
    SoftwareVersionOut,
)

app = MCPProxy(
    contact={
        'email': 'contact@namsor.com',
        'name': 'Namsor SAS',
        'url': 'http://www.namsor.com/',
        'x-twitter': 'gendreapp',
    },
    description="NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. By default, enpoints use 1 unit per name (ex. Gender), but Ethnicity classification uses 10 to 20 units per name depending on taxonomy. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it! ",
    license={
        'name': 'NamSorAPI_Lic_v0.0.7',
        'url': 'https://v2.namsor.com/NamSorAPIv2/assets/pdf/201803_NamSor_API_Terms_v007.pdf',
    },
    title='NamSor API v2',
    version='2.0.24',
    servers=[
        {
            'description': 'namsor_v2',
            'url': 'https://v2.namsor.com/NamSorAPIv2',
            'variables': {},
        }
    ],
)


@app.get(
    '/api2/json/anonymize/{source}/{anonymized}/{token}',
    tags=['data_anonymization'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def anonymize(source: str, anonymized: bool = ..., token: str = ...):
    """
    Activate/deactivate anonymization for a source.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/apiKeyInfo',
    tags=['api_usage_management'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def api_key_info():
    """
    Read API Key info.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/apiServices',
    tags=[
        'api_usage_management',
        'cross_border_name_interaction',
        'country_inference_by_name',
        'name_ethnicity_prediction',
        'name_origin_and_type_inference',
        'software_version_information',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def available_services():
    """
    List of classification services and usage cost in Units per classification (default is 1=ONE Unit). Some API endpoints (ex. Corridor) combine multiple classifiers.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/apiStatus',
    tags=['api_usage_management', 'software_version_information'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def api_status():
    """
    Prints the current status of the classifiers. A classifier name in apiStatus corresponds to a service name in apiServices.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/apiUsage',
    tags=['api_usage_management'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def api_usage():
    """
    Print current API usage.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/apiUsageHistory',
    tags=['api_usage_management'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def api_usage_history():
    """
    Print historical API usage.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/apiUsageHistoryAggregate',
    tags=['api_usage_management'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def api_usage_history_aggregate():
    """
    Print historical API usage (in an aggregated view, by service, by day/hour/min).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/castegroupIndianFull/{subDivisionIso31662}/{personalNameFull}',
    tags=[
        'indian_name_classification',
        'indian_name_subclassification',
        'religion_prediction_by_name',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def castegroup_indian_full(
    sub_division_iso31662: str = Path(..., alias='subDivisionIso31662'),
    personal_name_full: str = Path(..., alias='personalNameFull'),
):
    """
    [USES 10 UNITS PER NAME] Infer the likely Indian name castegroup of a personal full name.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/castegroupIndianFullBatch',
    tags=[
        'indian_name_classification',
        'religion_prediction_by_name',
        'indian_name_subclassification',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def castegroup_indian_full_batch(body: BatchPersonalNameSubdivisionIn = None):
    """
    [USES 10 UNITS PER NAME] Infer the likely Indian name castegroup of up to 100 personal full names.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/chineseNameCandidates/{chineseSurnameLatin}/{chineseGivenNameLatin}',
    tags=['chinese_name_classification', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def chinese_name_candidates(
    chinese_surname_latin: str = Path(..., alias='chineseSurnameLatin'),
    chinese_given_name_latin: str = Path(..., alias='chineseGivenNameLatin'),
):
    """
    Identify Chinese name candidates, based on the romanized name ex. Wang Xiaoming
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/chineseNameCandidatesBatch',
    tags=['chinese_name_classification', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def chinese_name_candidates_batch(body: BatchFirstLastNameIn = None):
    """
    Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname), ex. Wang Xiaoming
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/chineseNameCandidatesGenderBatch',
    tags=[
        'chinese_name_classification',
        'gender_prediction_by_name',
        'name_structure_analysis',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def chinese_name_candidates_gender_batch(body: BatchFirstLastNameGenderIn = None):
    """
    Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname) ex. Wang Xiaoming.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/chineseNameGenderCandidates/{chineseSurnameLatin}/{chineseGivenNameLatin}/{knownGender}',
    tags=['chinese_name_classification', 'gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def chinese_name_gender_candidates(
    chinese_surname_latin: str = Path(..., alias='chineseSurnameLatin'),
    chinese_given_name_latin: str = Path(..., alias='chineseGivenNameLatin'),
    known_gender: str = Path(..., alias='knownGender'),
):
    """
    Identify Chinese name candidates, based on the romanized name ex. Wang Xiaoming - having a known gender ('male' or 'female')
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/chineseNameMatch/{chineseSurnameLatin}/{chineseGivenNameLatin}/{chineseName}',
    tags=['chinese_name_classification', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def chinese_name_match(
    chinese_surname_latin: str = Path(..., alias='chineseSurnameLatin'),
    chinese_given_name_latin: str = Path(..., alias='chineseGivenNameLatin'),
    chinese_name: str = Path(..., alias='chineseName'),
):
    """
    Return a score for matching Chinese name ex. 王晓明 with a romanized name ex. Wang Xiaoming
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/chineseNameMatchBatch',
    tags=['chinese_name_classification', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def chinese_name_match_batch(body: BatchMatchPersonalFirstLastNameIn = None):
    """
    Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname), ex. Wang Xiaoming
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/corridor/{countryIso2From}/{firstNameFrom}/{lastNameFrom}/{countryIso2To}/{firstNameTo}/{lastNameTo}',
    tags=['cross_border_name_interaction', 'name_origin_and_type_inference'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def corridor(
    country_iso2_from: str = Path(..., alias='countryIso2From'),
    first_name_from: str = Path(..., alias='firstNameFrom'),
    last_name_from: str = Path(..., alias='lastNameFrom'),
    country_iso2_to: str = Path(..., alias='countryIso2To'),
    first_name_to: str = Path(..., alias='firstNameTo'),
    last_name_to: str = Path(..., alias='lastNameTo'),
):
    """
    [USES 20 UNITS PER NAME COUPLE] Infer several classifications for a cross border interaction between names (ex. remit, travel, intl com)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/corridorBatch',
    tags=['cross_border_name_interaction', 'country_inference_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def corridor_batch(body: BatchCorridorIn = None):
    """
    [USES 20 UNITS PER NAME PAIR] Infer several classifications for up to 100 cross border interaction between names (ex. remit, travel, intl com)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/country/{personalNameFull}',
    tags=['country_inference_by_name', 'name_origin_and_type_inference'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def country(personal_name_full: str = Path(..., alias='personalNameFull')):
    """
    [USES 10 UNITS PER NAME] Infer the likely country of residence of a personal full name, or one surname. Assumes names as they are in the country of residence OR the country of origin.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/countryBatch',
    tags=['country_inference_by_name', 'name_origin_and_type_inference'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def country_batch(body: BatchPersonalNameIn = None):
    """
    [USES 10 UNITS PER NAME] Infer the likely country of residence of up to 100 personal full names, or surnames. Assumes names as they are in the country of residence OR the country of origin.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/diaspora/{countryIso2}/{firstName}/{lastName}',
    tags=['name_ethnicity_prediction', 'country_inference_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def diaspora(
    country_iso2: str = Path(..., alias='countryIso2'),
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
):
    """
    [USES 20 UNITS PER NAME] Infer the likely ethnicity/diaspora of a personal name, given a country of residence ISO2 code (ex. US, CA, AU, NZ etc.)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/diasporaBatch',
    tags=[
        'name_ethnicity_prediction',
        'country_inference_by_name',
        'cross_border_name_interaction',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def diaspora_batch(body: BatchFirstLastNameGeoIn = None):
    """
    [USES 20 UNITS PER NAME] Infer the likely ethnicity/diaspora of up to 100 personal names, given a country of residence ISO2 code (ex. US, CA, AU, NZ etc.)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/gender/{firstName}',
    tags=[
        'gender_prediction_by_name',
        'name_ethnicity_prediction',
        'country_inference_by_name',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender(first_name: str = Path(..., alias='firstName')):
    """
    Infer the likely gender of a just a fiven name, assuming default 'US' local context. Please use preferably full names and local geographic context for better accuracy.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/gender/{firstName}/{lastName}',
    tags=['gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_1(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
):
    """
    Infer the likely gender of a name.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderBatch',
    tags=[
        'gender_prediction_by_name',
        'name_ethnicity_prediction',
        'cross_border_name_interaction',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_batch(body: BatchFirstLastNameIn = None):
    """
    Infer the likely gender of up to 100 names, detecting automatically the cultural context.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/genderChineseName/{chineseName}',
    tags=['chinese_name_classification', 'gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_chinese_name(chinese_name: str = Path(..., alias='chineseName')):
    """
    Infer the likely gender of a Chinese full name ex. 王晓明
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderChineseNameBatch',
    tags=['gender_prediction_by_name', 'chinese_name_classification'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_chinese_name_batch(body: BatchPersonalNameIn = None):
    """
    Infer the likely gender of up to 100 full names ex. 王晓明
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/genderChineseNamePinyin/{chineseSurnameLatin}/{chineseGivenNameLatin}',
    tags=['chinese_name_classification', 'gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_chinese_name_pinyin(
    chinese_surname_latin: str = Path(..., alias='chineseSurnameLatin'),
    chinese_given_name_latin: str = Path(..., alias='chineseGivenNameLatin'),
):
    """
    Infer the likely gender of a Chinese name in LATIN (Pinyin).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderChineseNamePinyinBatch',
    tags=['chinese_name_classification', 'gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_chinese_name_pinyin_batch(body: BatchFirstLastNameIn = None):
    """
    Infer the likely gender of up to 100 Chinese names in LATIN (Pinyin).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/genderFull/{fullName}',
    tags=['gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_full(full_name: str = Path(..., alias='fullName')):
    """
    Infer the likely gender of a full name, ex. John H. Smith
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderFullBatch',
    tags=[
        'gender_prediction_by_name',
        'name_ethnicity_prediction',
        'country_inference_by_name',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_full_batch(body: BatchPersonalNameIn = None):
    """
    Infer the likely gender of up to 100 full names, detecting automatically the cultural context.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/genderFullGeo/{fullName}/{countryIso2}',
    tags=[
        'gender_prediction_by_name',
        'name_ethnicity_prediction',
        'country_inference_by_name',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_full_geo(
    full_name: str = Path(..., alias='fullName'),
    country_iso2: str = Path(..., alias='countryIso2'),
):
    """
    Infer the likely gender of a full name, given a local context (ISO2 country code).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderFullGeoBatch',
    tags=[
        'gender_prediction_by_name',
        'country_inference_by_name',
        'name_ethnicity_prediction',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_full_geo_batch(body: BatchPersonalNameGeoIn = None):
    """
    Infer the likely gender of up to 100 full names, with a given cultural context (country ISO2 code).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/genderGeo/{firstName}/{lastName}/{countryIso2}',
    tags=['gender_prediction_by_name', 'country_inference_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_geo(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
    country_iso2: str = Path(..., alias='countryIso2'),
):
    """
    Infer the likely gender of a name, given a local context (ISO2 country code).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderGeoBatch',
    tags=['gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_geo_batch(body: BatchFirstLastNameGeoIn = None):
    """
    Infer the likely gender of up to 100 names, each given a local context (ISO2 country code).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/genderJapaneseName/{japaneseSurname}/{japaneseGivenName}',
    tags=['gender_prediction_by_name', 'japanese_name_handling'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_japanese_name_pinyin(
    japanese_surname: str = Path(..., alias='japaneseSurname'),
    japanese_given_name: str = Path(..., alias='japaneseGivenName'),
):
    """
    Infer the likely gender of a Japanese name in LATIN (Pinyin).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderJapaneseNameBatch',
    tags=[
        'gender_prediction_by_name',
        'japanese_name_handling',
        'name_structure_analysis',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_japanese_name_pinyin_batch(body: BatchFirstLastNameIn = None):
    """
    Infer the likely gender of up to 100 Japanese names in LATIN (Pinyin).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/genderJapaneseNameFull/{japaneseName}',
    tags=[
        'gender_prediction_by_name',
        'japanese_name_handling',
        'name_structure_analysis',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_japanese_name_full(japanese_name: str = Path(..., alias='japaneseName')):
    """
    Infer the likely gender of a Japanese full name ex. 王晓明
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/genderJapaneseNameFullBatch',
    tags=['gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def gender_japanese_name_full_batch(body: BatchPersonalNameIn = None):
    """
    Infer the likely gender of up to 100 full names
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/japaneseNameGenderKanjiCandidatesBatch',
    tags=[
        'japanese_name_handling',
        'gender_prediction_by_name',
        'name_structure_analysis',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_gender_kanji_candidates_batch(
    body: BatchFirstLastNameGenderIn = None,
):
    """
    Identify japanese name candidates in KANJI, based on the romanized name (firstName = japaneseGivenName; lastName=japaneseSurname) with KNOWN gender, ex. Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/japaneseNameKanjiCandidates/{japaneseSurnameLatin}/{japaneseGivenNameLatin}',
    tags=['japanese_name_handling', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_kanji_candidates(
    japanese_surname_latin: str = Path(..., alias='japaneseSurnameLatin'),
    japanese_given_name_latin: str = Path(..., alias='japaneseGivenNameLatin'),
):
    """
    Identify japanese name candidates in KANJI, based on the romanized name ex. Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/japaneseNameKanjiCandidates/{japaneseSurnameLatin}/{japaneseGivenNameLatin}/{knownGender}',
    tags=['japanese_name_handling', 'gender_prediction_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_kanji_candidates_1(
    japanese_surname_latin: str = Path(..., alias='japaneseSurnameLatin'),
    japanese_given_name_latin: str = Path(..., alias='japaneseGivenNameLatin'),
    known_gender: str = Path(..., alias='knownGender'),
):
    """
    Identify japanese name candidates in KANJI, based on the romanized name ex. Yamamoto Sanae - and a known gender.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/japaneseNameKanjiCandidatesBatch',
    tags=['japanese_name_handling', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_kanji_candidates_batch(body: BatchFirstLastNameIn = None):
    """
    Identify japanese name candidates in KANJI, based on the romanized name (firstName = japaneseGivenName; lastName=japaneseSurname), ex. Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/japaneseNameLatinCandidates/{japaneseSurnameKanji}/{japaneseGivenNameKanji}',
    tags=['japanese_name_handling', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_latin_candidates(
    japanese_surname_kanji: str = Path(..., alias='japaneseSurnameKanji'),
    japanese_given_name_kanji: str = Path(..., alias='japaneseGivenNameKanji'),
):
    """
    Romanize japanese name, based on the name in Kanji.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/japaneseNameLatinCandidatesBatch',
    tags=['japanese_name_handling', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_latin_candidates_batch(body: BatchFirstLastNameIn = None):
    """
    Romanize japanese names, based on the name in KANJI
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/japaneseNameMatch/{japaneseSurnameLatin}/{japaneseGivenNameLatin}/{japaneseName}',
    tags=['japanese_name_handling', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_match(
    japanese_surname_latin: str = Path(..., alias='japaneseSurnameLatin'),
    japanese_given_name_latin: str = Path(..., alias='japaneseGivenNameLatin'),
    japanese_name: str = Path(..., alias='japaneseName'),
):
    """
    Return a score for matching Japanese name in KANJI ex. 山本 早苗 with a romanized name ex. Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/japaneseNameMatchBatch',
    tags=['japanese_name_handling', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_match_batch(body: BatchMatchPersonalFirstLastNameIn = None):
    """
    Return a score for matching a list of Japanese names in KANJI ex. 山本 早苗 with romanized names ex. Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/japaneseNameMatchFeedbackLoop/{japaneseSurnameLatin}/{japaneseGivenNameLatin}/{japaneseName}',
    tags=['japanese_name_handling', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def japanese_name_match_feedback_loop(
    japanese_surname_latin: str = Path(..., alias='japaneseSurnameLatin'),
    japanese_given_name_latin: str = Path(..., alias='japaneseGivenNameLatin'),
    japanese_name: str = Path(..., alias='japaneseName'),
):
    """
    [CREDITS 1 UNIT] Feedback loop to better perform matching Japanese name in KANJI ex. 山本 早苗 with a romanized name ex. Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/learnable/{source}/{learnable}/{token}',
    tags=['api_usage_management'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def learnable(source: str, learnable: bool = ..., token: str = ...):
    """
    Activate/deactivate learning from a source.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/nameType/{properNoun}',
    tags=[
        'name_origin_and_type_inference',
        'name_ethnicity_prediction',
        'country_inference_by_name',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def name_type(proper_noun: str = Path(..., alias='properNoun')):
    """
    Infer the likely type of a proper noun (personal name, brand name, place name etc.)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/nameTypeBatch',
    tags=[
        'name_origin_and_type_inference',
        'country_inference_by_name',
        'name_ethnicity_prediction',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def name_type_batch(body: BatchNameIn = None):
    """
    Infer the likely common type of up to 100 proper nouns (personal name, brand name, place name etc.)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/nameTypeGeo/{properNoun}/{countryIso2}',
    tags=['name_origin_and_type_inference', 'country_inference_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def name_type_geo(
    proper_noun: str = Path(..., alias='properNoun'),
    country_iso2: str = Path(..., alias='countryIso2'),
):
    """
    Infer the likely type of a proper noun (personal name, brand name, place name etc.)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/nameTypeGeoBatch',
    tags=[
        'name_origin_and_type_inference',
        'country_inference_by_name',
        'name_ethnicity_prediction',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def name_type_geo_batch(body: BatchNameGeoIn = None):
    """
    Infer the likely common type of up to 100 proper nouns (personal name, brand name, place name etc.)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/origin/{firstName}/{lastName}',
    tags=['country_inference_by_name', 'name_origin_and_type_inference'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def origin(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
):
    """
    [USES 10 UNITS PER NAME] Infer the likely country of origin of a personal name. Assumes names as they are in the country of origin. For US, CA, AU, NZ and other melting-pots : use 'diaspora' instead.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/originBatch',
    tags=[
        'country_inference_by_name',
        'name_origin_and_type_inference',
        'name_ethnicity_prediction',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def origin_batch(body: BatchFirstLastNameIn = None):
    """
    [USES 10 UNITS PER NAME] Infer the likely country of origin of up to 100 names, detecting automatically the cultural context.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/parseChineseName/{chineseName}',
    tags=[
        'chinese_name_classification',
        'name_structure_analysis',
        'personal_name_structure_parsing',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_chinese_name(chinese_name: str = Path(..., alias='chineseName')):
    """
    Infer the likely first/last name structure of a name, ex. 王晓明 -> 王(surname) 晓明(given name)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/parseChineseNameBatch',
    tags=[
        'chinese_name_classification',
        'name_structure_analysis',
        'personal_name_structure_parsing',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_chinese_name_batch(body: BatchPersonalNameIn = None):
    """
    Infer the likely first/last name structure of a name, ex. 王晓明 -> 王(surname) 晓明(given name).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/parseJapaneseName/{japaneseName}',
    tags=[
        'japanese_name_handling',
        'name_structure_analysis',
        'personal_name_structure_parsing',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_japanese_name(japanese_name: str = Path(..., alias='japaneseName')):
    """
    Infer the likely first/last name structure of a name, ex. 山本 早苗 or Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/parseJapaneseNameBatch',
    tags=[
        'name_structure_analysis',
        'personal_name_structure_parsing',
        'japanese_name_handling',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_japanese_name_batch(body: BatchPersonalNameIn = None):
    """
    Infer the likely first/last name structure of a name, ex. 山本 早苗 or Yamamoto Sanae
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/parseName/{nameFull}',
    tags=['name_structure_analysis', 'personal_name_structure_parsing'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_name(name_full: str = Path(..., alias='nameFull')):
    """
    Infer the likely first/last name structure of a name, ex. John Smith or SMITH, John or SMITH; John.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/parseName/{nameFull}/{countryIso2}',
    tags=[
        'name_structure_analysis',
        'personal_name_structure_parsing',
        'country_inference_by_name',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_name_geo(
    name_full: str = Path(..., alias='nameFull'),
    country_iso2: str = Path(..., alias='countryIso2'),
):
    """
    Infer the likely first/last name structure of a name, ex. John Smith or SMITH, John or SMITH; John. For better accuracy, provide a geographic context.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/parseNameBatch',
    tags=['name_structure_analysis', 'personal_name_structure_parsing'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_name_batch(body: BatchPersonalNameIn = None):
    """
    Infer the likely first/last name structure of a name, ex. John Smith or SMITH, John or SMITH; John.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/parseNameGeoBatch',
    tags=['name_structure_analysis', 'personal_name_structure_parsing'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def parse_name_geo_batch(body: BatchPersonalNameGeoIn = None):
    """
    Infer the likely first/last name structure of a name, ex. John Smith or SMITH, John or SMITH; John. Giving a local context improves precision.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/phoneCode/{firstName}/{lastName}/{phoneNumber}',
    tags=['country_inference_by_name', 'phone_code_and_prefix_inference'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def phone_code(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
    phone_number: str = Path(..., alias='phoneNumber'),
):
    """
    [USES 11 UNITS PER NAME] Infer the likely country and phone prefix, given a personal name and formatted / unformatted phone number.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/phoneCodeBatch',
    tags=['country_inference_by_name', 'phone_code_and_prefix_inference'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def phone_code_batch(body: BatchFirstLastNamePhoneNumberIn = None):
    """
    [USES 11 UNITS PER NAME] Infer the likely country and phone prefix, of up to 100 personal names, detecting automatically the local context given a name and formatted / unformatted phone number.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/phoneCodeGeo/{firstName}/{lastName}/{phoneNumber}/{countryIso2}',
    tags=['phone_code_and_prefix_inference', 'country_inference_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def phone_code_geo(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
    phone_number: str = Path(..., alias='phoneNumber'),
    country_iso2: str = Path(..., alias='countryIso2'),
):
    """
    [USES 11 UNITS PER NAME] Infer the likely phone prefix, given a personal name and formatted / unformatted phone number, with a local context (ISO2 country of residence).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/phoneCodeGeoBatch',
    tags=['country_inference_by_name', 'phone_code_and_prefix_inference'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def phone_code_geo_batch(body: BatchFirstLastNamePhoneNumberGeoIn = None):
    """
    [USES 11 UNITS PER NAME] Infer the likely country and phone prefix, of up to 100 personal names, with a local context (ISO2 country of residence).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/phoneCodeGeoFeedbackLoop/{firstName}/{lastName}/{phoneNumber}/{phoneNumberE164}/{countryIso2}',
    tags=['phone_code_and_prefix_inference', 'country_inference_by_name'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def phone_code_geo_feedback_loop(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
    phone_number: str = Path(..., alias='phoneNumber'),
    phone_number_e164: str = Path(..., alias='phoneNumberE164'),
    country_iso2: str = Path(..., alias='countryIso2'),
):
    """
    [CREDITS 1 UNIT] Feedback loop to better infer the likely phone prefix, given a personal name and formatted / unformatted phone number, with a local context (ISO2 country of residence).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/pinyinChineseName/{chineseName}',
    tags=['chinese_name_classification', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def pinyin_chinese_name(chinese_name: str = Path(..., alias='chineseName')):
    """
    Romanize the Chinese name to Pinyin, ex. 王晓明 -> Wang (surname) Xiaoming (given name)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/pinyinChineseNameBatch',
    tags=['chinese_name_classification', 'name_structure_analysis'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def pinyin_chinese_name_batch(body: BatchPersonalNameIn = None):
    """
    Romanize a list of Chinese name to Pinyin, ex. 王晓明 -> Wang (surname) Xiaoming (given name).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/regions',
    tags=['software_version_information'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def regions():
    """
    Print basic source statistics.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/religionFull/{countryIso2}/{subDivisionIso31662}/{personalNameFull}',
    tags=['religion_prediction_by_name', 'indian_name_classification'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def religion_full(
    country_iso2: str = Path(..., alias='countryIso2'),
    sub_division_iso31662: str = Path(..., alias='subDivisionIso31662'),
    personal_name_full: str = Path(..., alias='personalNameFull'),
):
    """
    [USES 10 UNITS PER NAME] Infer the likely religion of a personal full name. NB: only for INDIA (as of current version).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/religionFullBatch',
    tags=[
        'indian_name_classification',
        'religion_prediction_by_name',
        'indian_name_subclassification',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def religion_full_batch(body: BatchPersonalNameGeoSubdivisionIn = None):
    """
    [USES 10 UNITS PER NAME] Infer the likely religion of up to 100 personal full names. NB: only for India as of currently.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/religionIndianFull/{subDivisionIso31662}/{personalNameFull}',
    tags=[
        'indian_name_classification',
        'religion_prediction_by_name',
        'indian_name_subclassification',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def religion(
    sub_division_iso31662: str = Path(..., alias='subDivisionIso31662'),
    personal_name_full: str = Path(..., alias='personalNameFull'),
):
    """
    [USES 10 UNITS PER NAME] Infer the likely religion of a personal Indian full name, provided the Indian state or Union territory (NB/ this can be inferred using the subclassification endpoint).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/religionIndianFullBatch',
    tags=[
        'indian_name_classification',
        'religion_prediction_by_name',
        'indian_name_subclassification',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def religion_indian_full_batch(body: BatchPersonalNameSubdivisionIn = None):
    """
    [USES 10 UNITS PER NAME] Infer the likely religion of up to 100 personal full Indian names, provided the subclassification at State or Union territory level (NB/ can be inferred using the subclassification endpoint).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/softwareVersion',
    tags=['software_version_information'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def software_version():
    """
    Get the current software version
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/subclassification/{countryIso2}/{firstName}/{lastName}',
    tags=['indian_name_subclassification', 'indian_name_classification'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def subclassification(
    country_iso2: str = Path(..., alias='countryIso2'),
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
):
    """
    [USES 10 UNITS PER NAME] Infer the likely origin of a name at a country subclassification level (state or regeion). Initially, this is only supported for India (ISO2 code 'IN').
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/subclassificationBatch',
    tags=[
        'indian_name_subclassification',
        'indian_name_classification',
        'name_origin_and_type_inference',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def subclassification_batch(body: BatchFirstLastNameGeoIn = None):
    """
    [USES 10 UNITS PER NAME] Infer the likely origin of a list of up to 100 names at a country subclassification level (state or regeion). Initially, this is only supported for India (ISO2 code 'IN').
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/subclassificationIndian/{firstName}/{lastName}',
    tags=['indian_name_classification', 'indian_name_subclassification'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def subclassification_indian(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
):
    """
    [USES 10 UNITS PER NAME] Infer the likely Indian state of Union territory according to ISO 3166-2:IN based on the name.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/subclassificationIndianBatch',
    tags=[
        'indian_name_classification',
        'indian_name_subclassification',
        'country_inference_by_name',
    ],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def subclassification_indian_batch(body: BatchFirstLastNameGeoIn = None):
    """
    [USES 10 UNITS PER NAME] Infer the likely Indian state of Union territory according to ISO 3166-2:IN based on a list of up to 100 names.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/taxonomyClasses/{classifierName}',
    tags=['software_version_information'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def taxonomy_classes(classifier_name: str = Path(..., alias='classifierName')):
    """
    Print the taxonomy classes valid for the given classifier.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/usRaceEthnicity/{firstName}/{lastName}',
    tags=['us_name_ethnicity_inference', 'name_ethnicity_prediction'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def us_race_ethnicity(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
):
    """
    [USES 10 UNITS PER NAME] Infer a US resident's likely race/ethnicity according to US Census taxonomy W_NL (white, non latino), HL (hispano latino),  A (asian, non latino), B_NL (black, non latino). Optionally add header X-OPTION-USRACEETHNICITY-TAXONOMY: USRACEETHNICITY-6CLASSES for two additional classes, AI_AN (American Indian or Alaskan Native) and PI (Pacific Islander).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/usRaceEthnicityBatch',
    tags=['us_name_ethnicity_inference', 'name_ethnicity_prediction'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def us_race_ethnicity_batch(body: BatchFirstLastNameGeoIn = None):
    """
    [USES 10 UNITS PER NAME] Infer up-to 100 US resident's likely race/ethnicity according to US Census taxonomy. Output is W_NL (white, non latino), HL (hispano latino),  A (asian, non latino), B_NL (black, non latino). Optionally add header X-OPTION-USRACEETHNICITY-TAXONOMY: USRACEETHNICITY-6CLASSES for two additional classes, AI_AN (American Indian or Alaskan Native) and PI (Pacific Islander).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api2/json/usRaceEthnicityZIP5/{firstName}/{lastName}/{zip5Code}',
    tags=['us_name_ethnicity_inference', 'name_ethnicity_prediction'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def us_race_ethnicity_z_i_p5(
    first_name: str = Path(..., alias='firstName'),
    last_name: str = Path(..., alias='lastName'),
    zip5_code: str = Path(..., alias='zip5Code'),
):
    """
    [USES 10 UNITS PER NAME] Infer a US resident's likely race/ethnicity according to US Census taxonomy, using (optional) ZIP5 code info. Output is W_NL (white, non latino), HL (hispano latino),  A (asian, non latino), B_NL (black, non latino). Optionally add header X-OPTION-USRACEETHNICITY-TAXONOMY: USRACEETHNICITY-6CLASSES for two additional classes, AI_AN (American Indian or Alaskan Native) and PI (Pacific Islander).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/api2/json/usZipRaceEthnicityBatch',
    tags=['us_name_ethnicity_inference', 'name_ethnicity_prediction'],
    security=[
        APIKeyHeader(name="X-API-KEY"),
    ],
)
def us_zip_race_ethnicity_batch(body: BatchFirstLastNameGeoZippedIn = None):
    """
    [USES 10 UNITS PER NAME] Infer up-to 100 US resident's likely race/ethnicity according to US Census taxonomy, with (optional) ZIP code. Output is W_NL (white, non latino), HL (hispano latino),  A (asian, non latino), B_NL (black, non latino). Optionally add header X-OPTION-USRACEETHNICITY-TAXONOMY: USRACEETHNICITY-6CLASSES for two additional classes, AI_AN (American Indian or Alaskan Native) and PI (Pacific Islander).
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
