# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:04:23+00:00

from __future__ import annotations

from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field, confloat


class APIBillingPeriodUsageOut(BaseModel):
    apiKey: Optional[str] = Field(None, description='User API Key.')
    billingStatus: Optional[str] = Field(
        None, description='Current period billing status ex OPEN.'
    )
    hardLimit: Optional[int] = Field(
        None,
        description='Current period hard limit (reaching the limit sends an email notification and blocks the API Key).',
    )
    periodEnded: Optional[int] = Field(
        None, description="Datetime when the the plan's current period endend."
    )
    periodStarted: Optional[int] = Field(
        None, description="Datetime when the the plan's current period started."
    )
    softLimit: Optional[int] = Field(
        None,
        description='Current period soft limit (reaching the limit sends an email notification).',
    )
    stripeCurrentPeriodEnd: Optional[int] = Field(
        None,
        description="Datetime when the the plan's current period endend (in Stripe). Internal and Stripe periodicity should ~coincide.",
    )
    stripeCurrentPeriodStart: Optional[int] = Field(
        None,
        description="Datetime when the the plan's current period started (in Stripe). Internal and Stripe periodicity should ~coincide.",
    )
    subscriptionStarted: Optional[int] = Field(
        None, description='Datetime when the user subscribed to the plan.'
    )
    usage: Optional[int] = Field(
        None,
        description='Current period usage in units (NB some API endpoints use more than one unit).',
    )


class APIClassifierOut(BaseModel):
    classifierName: Optional[str] = Field(None, description='The classifier name')
    learning: Optional[bool] = Field(
        None, description='True if the classifier is learning'
    )
    probabilityCalibrated: Optional[bool] = Field(
        None,
        description='True if the classifier has finished the initial learning and calibrated probabilities (meanwhile, during initial learning, probabilities will be equal to -1)',
    )
    serving: Optional[bool] = Field(
        None,
        description='True if the classifier is serving requests (has reached minimal learning, is not shutting down)',
    )
    shuttingDown: Optional[bool] = Field(
        None, description='True if the classifier is shutting down'
    )


class APIClassifierTaxonomyOut(BaseModel):
    classifierName: Optional[str] = Field(
        None,
        description='Name of the classifier as per apiStatus (corresponds also to the name of the service in apiServices)',
    )
    classifyingScripts: Optional[List[str]] = Field(
        None, description='The scripts / alphabets this classifiers classifies to'
    )
    taxonomyClasses: Optional[List[str]] = Field(
        None, description='The taxonomy classes this classifier classifies to'
    )


class APIKeyOut(BaseModel):
    admin: Optional[bool] = Field(None, description='The API Key has admin role.')
    anonymized: Optional[bool] = Field(
        None,
        description="The API Key is anonymized (using SHA-252 digest for logging). Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).",
    )
    apiKey: Optional[str] = Field(None, description='The user API Key.')
    corporate: Optional[bool] = Field(
        None,
        description='The API Key has role corporate (ex SWIFT payments instead of Stripe payments).',
    )
    disabled: Optional[bool] = Field(
        None, description='The API Key is temporarily or permanently disabled.'
    )
    learnable: Optional[bool] = Field(
        None,
        description="The API Key is learnable (without assuming truthfulness) for machine learning. Set learnable=false and anonymized=true for highest privacy (ie. to forget data as it's processed).",
    )
    partner: Optional[bool] = Field(None, description='The API Key has partner role.')
    striped: Optional[bool] = Field(
        None, description='The API Key is associated to a valid Stripe account.'
    )
    userId: Optional[str] = Field(None, description='The user identifier.')
    vetted: Optional[bool] = Field(
        None,
        description='The API Key is vetted (assumed truthful) for machine learning.',
    )


class APIPlanSubscriptionOut(BaseModel):
    apiKey: Optional[str] = Field(None, description='User API Key.')
    currency: Optional[str] = Field(
        None, description='Current plan Currency for prices.'
    )
    currencyFactor: Optional[float] = Field(
        None, description='For USD, GBP, EUR - the factor is 1.'
    )
    planBaseFeesKey: Optional[str] = Field(
        None, description='Current plan key (as in Stripe product).'
    )
    planEnded: Optional[int] = Field(
        None, description='Datetime when the user ended the plan.'
    )
    planName: Optional[str] = Field(None, description='Current plan name.')
    planQuota: Optional[int] = Field(
        None,
        description='Current plan quota in quantity of units (NB: some API use several units per name).',
    )
    planStarted: Optional[int] = Field(
        None, description='Datetime when the user subscribed to the current plan.'
    )
    planStatus: Optional[str] = Field(None, description='Plan status.')
    price: Optional[float] = Field(
        None,
        description='Current plan price for overages expressed in Currency (extra price per unit above the free quota).',
    )
    priceOverage: Optional[float] = Field(
        None,
        description='Current plan price for overages expressed in Currency (extra price per unit above the free quota).',
    )
    priceOverageUSD: Optional[float] = Field(
        None,
        description='Current plan price for overages expressed in USD (extra price per unit above the free quota).',
    )
    priceUSD: Optional[float] = Field(
        None,
        description='Current plan monthly price expressed in USD (includes a free quota).',
    )
    priorPlanStarted: Optional[int] = Field(
        None, description='Datetime when the user subscribed to the prior plan.'
    )
    stripeCustomerId: Optional[str] = Field(
        None, description='Stripe customer identifier.'
    )
    stripeStatus: Optional[str] = Field(None, description='Stripe status ex active.')
    stripeSubscription: Optional[str] = Field(
        None, description='Stripe subscription identifier.'
    )
    taxRate: Optional[float] = Field(
        None, description='Applicable tax rate for the plan.'
    )
    userId: Optional[str] = Field(None, description='Internal user identifier.')


class APIServiceOut(BaseModel):
    costInUnits: Optional[int] = Field(
        None,
        description='Indicates how many units per call this service costs (ex. the number of units per name)',
    )
    serviceGroup: Optional[str] = Field(
        None,
        description='Groups together classifiers providing a similar service (ex. gender groups personalname_gender and personalfullname_gender)',
    )
    serviceName: Optional[str] = Field(
        None,
        description='A service name corresponds to classifier name in apiStatus (ex. personalname_gender or personalfullname_gender)',
    )


class APIServicesOut(BaseModel):
    apiServices: Optional[List[APIServiceOut]] = Field(
        None, description='List of API Services'
    )


class APIUsageAggregatedOut(BaseModel):
    colHeaders: Optional[List[str]] = Field(
        None, description='apiServices as column headers '
    )
    data: Optional[List[List[int]]] = Field(
        None,
        description='Data points : usage per DAY, WEEK or MONTH and per apiService',
    )
    historyTruncated: Optional[bool] = Field(
        None, description='If the history was truncaded due to data limit'
    )
    periodEnd: Optional[int] = Field(
        None, description='End datetime of the reporting period'
    )
    periodStart: Optional[int] = Field(
        None, description='Start datetime of the reporting period'
    )
    rowHeaders: Optional[List[str]] = Field(None, description='dates as row headers ')
    timeUnit: Optional[str] = Field(
        None, description='Time unit is DAY, WEEK or MONTH depending on prior usage'
    )
    totalUsage: Optional[int] = Field(
        None, description='Total usage in the current period'
    )


class FactIn(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class FeedbackLoopOut(BaseModel):
    feedbackCredits: Optional[int] = Field(
        None,
        description='Number of units recredited as per feedback loop successful classification',
    )


class FirstLastNameDiasporaedOut(BaseModel):
    countryIso2: Optional[str] = Field(
        None,
        description='From input data, the countryIso2 of geographic context (US,CA etc.)',
    )
    ethnicitiesTop: Optional[List[str]] = Field(
        None, description='List most likely ethnicities (top 10)'
    )
    ethnicity: Optional[str] = Field(
        None, description='The most likely ethnicity', examples=['Chinese']
    )
    ethnicityAlt: Optional[str] = Field(
        None, description='The second best alternative ethnicity', examples=['Japanese']
    )
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    id: Optional[str] = None
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    lifted: Optional[bool] = Field(
        None,
        description='Indicates if the output ethnicity is based on machine learning only, or further lifted as a known fact by a country-specific rule. Let us know if you believe ethnicity is incorrect on a specific case where lifted is true.',
    )
    probabilityAltCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for ethnicity OR ethnicityAlt to have been guessed correctly. -1 = still calibrating. ',
    )
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for ethnicity to have been guessed correctly. -1 = still calibrating. ',
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Compatibility to NamSor_v1 Diaspora score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class FirstLastNameGenderIn(BaseModel):
    firstName: Optional[str] = None
    gender: Optional[str] = Field(None, description='The known gender of the name')
    id: Optional[str] = None
    lastName: Optional[str] = None


class LikelyGender(Enum):
    male = 'male'
    female = 'female'
    unknown = 'unknown'


class FirstLastNameGenderedOut(BaseModel):
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    genderScale: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None, description='Compatibility to NamSor_v1 Gender Scale M[-1..U..+1]F value.'
    )
    id: Optional[str] = None
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    likelyGender: Optional[LikelyGender] = Field(None, description='Most likely gender')
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for inferred gender to have been guessed correctly. -1 = still calibrating. ',
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Compatibility to NamSor_v1 Gender score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class FirstLastNameGeoIn(BaseModel):
    countryIso2: Optional[str] = None
    firstName: Optional[str] = None
    id: Optional[str] = None
    lastName: Optional[str] = None


class FirstLastNameGeoSubclassificationOut(BaseModel):
    countryIso2: Optional[str] = Field(None, description='The input country ISO2 code')
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    id: Optional[str] = None
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    probabilityAltCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for subclassification OR subclassificationAlt to have been guessed correctly. -1 = still calibrating. ',
    )
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for subclassification to have been guessed correctly. -1 = still calibrating. ',
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Compatibility to NamSor_v1 Origin score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None
    subClassification: Optional[str] = Field(
        None, description='Most likely subclassification ISO_3166-2 code'
    )
    subClassificationAlt: Optional[str] = Field(
        None, description='Second best alternative : subclassification ISO_3166-2 code'
    )
    subclassificationTop: Optional[List[str]] = Field(
        None, description='List subclassification ISO_3166-2 codes (top 10)'
    )


class FirstLastNameGeoZippedIn(BaseModel):
    countryIso2: Optional[str] = None
    firstName: Optional[str] = None
    id: Optional[str] = None
    lastName: Optional[str] = None
    zipCode: Optional[str] = None


class FirstLastNameIn(BaseModel):
    firstName: Optional[str] = None
    id: Optional[str] = None
    lastName: Optional[str] = None


class FirstLastNameOriginedOut(BaseModel):
    countriesOriginTop: Optional[List[str]] = Field(
        None, description='List countries of Origin (top 10)'
    )
    countryOrigin: Optional[str] = Field(
        None, description='Most likely country of Origin'
    )
    countryOriginAlt: Optional[str] = Field(
        None, description='Second best alternative : country of Origin'
    )
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    id: Optional[str] = None
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    probabilityAltCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for countryOrigin OR countryOriginAlt to have been guessed correctly. -1 = still calibrating. ',
    )
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for countryOrigin to have been guessed correctly. -1 = still calibrating. ',
    )
    regionOrigin: Optional[str] = Field(
        None,
        description='Most likely region of Origin (based on countryOrigin ISO2 code)',
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Compatibility to NamSor_v1 Origin score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None
    subRegionOrigin: Optional[str] = Field(
        None,
        description='Most likely sub region of Origin (based on countryOrigin ISO2 code)',
    )
    topRegionOrigin: Optional[str] = Field(
        None,
        description='Most likely top region of Origin (based on countryOrigin ISO2 code)',
    )


class FirstLastNameOut(BaseModel):
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    id: Optional[str] = None
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    script: Optional[str] = None


class FirstLastNamePhoneCodedOut(BaseModel):
    countryIso2: Optional[str] = None
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    id: Optional[str] = None
    internationalPhoneNumberVerified: Optional[str] = Field(
        None, description='The normalized phone number, verified using libphonenumber.'
    )
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    originCountryIso2: Optional[str] = Field(
        None, description='The likely country of origin of the name.'
    )
    originCountryIso2Alt: Optional[str] = Field(
        None, description='The best alternative country of origin of the name.'
    )
    phoneCountryCode: Optional[int] = Field(
        None,
        description='The phone country code of the phone number, verified using libphonenumber.',
    )
    phoneCountryCodeAlt: Optional[int] = Field(
        None, description='The best alternative phone country code of the phone number.'
    )
    phoneCountryIso2: Optional[str] = Field(
        None, description='The likely country of the phone number.'
    )
    phoneCountryIso2Alt: Optional[str] = Field(
        None, description='The best alternative country of the phone number.'
    )
    phoneCountryIso2Verified: Optional[str] = Field(
        None, description='The phone ISO2 country code, verified using libphonenumber.'
    )
    phoneNumber: Optional[str] = Field(None, description='The input phone number.')
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None
    verified: Optional[bool] = Field(
        None,
        description='Indicates if the phone number could be positively verified using libphonenumber.',
    )


class FirstLastNamePhoneNumberGeoIn(BaseModel):
    countryIso2: Optional[str] = None
    countryIso2Alt: Optional[str] = None
    firstName: Optional[str] = None
    id: Optional[str] = None
    lastName: Optional[str] = None
    phoneNumber: Optional[str] = None


class FirstLastNamePhoneNumberIn(BaseModel):
    firstName: Optional[str] = None
    id: Optional[str] = None
    lastName: Optional[str] = None
    phoneNumber: Optional[str] = None


class RaceEthnicity(Enum):
    W_NL = 'W_NL'
    HL = 'HL'
    A = 'A'
    B_NL = 'B_NL'
    AI_AN = 'AI_AN'
    PI = 'PI'


class RaceEthnicityAlt(Enum):
    W_NL = 'W_NL'
    HL = 'HL'
    A = 'A'
    B_NL = 'B_NL'
    AI_AN = 'AI_AN'
    PI = 'PI'


class FirstLastNameUSRaceEthnicityOut(BaseModel):
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    id: Optional[str] = None
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    probabilityAltCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for raceEthnicity OR raceEthnicityAlt to have been guessed correctly. -1 = still calibrating. ',
    )
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for raceEthnicity to have been guessed correctly. -1 = still calibrating. ',
    )
    raceEthnicitiesTop: Optional[List[str]] = Field(
        None, description="List 'race'/ethnicities"
    )
    raceEthnicity: Optional[RaceEthnicity] = Field(
        None, description="Most likely US 'race'/ethnicity"
    )
    raceEthnicityAlt: Optional[RaceEthnicityAlt] = Field(
        None, description="Second most likely US 'race'/ethnicity"
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class NameGeoIn(BaseModel):
    countryIso2: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None


class NameIn(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class NameMatchCandidateOut(BaseModel):
    candidateName: Optional[str] = Field(
        None, description='The name matching candidate name'
    )
    predScoreFamilyName: Optional[float] = Field(
        None, description='The family name prediction score.'
    )
    predScoreGivenName: Optional[float] = Field(
        None, description='The given name prediction score.'
    )
    probability: Optional[float] = Field(
        None, description='The name matching estimated probability.'
    )


class NameMatchCandidatesOut(BaseModel):
    firstName: Optional[str] = Field(
        None, description='The first name (also known as given name)'
    )
    id: Optional[str] = None
    lastName: Optional[str] = Field(
        None, description='The last name (also known as family name, or surname)'
    )
    matchCandidates: Optional[List[NameMatchCandidateOut]] = Field(
        None, description='The ordered list of name matching candidates'
    )
    orderOption: Optional[str] = Field(None, description='The option for ordering')
    script: Optional[str] = None


class MatchStatus(Enum):
    Match = 'Match'
    Mismatch = 'Mismatch'


class NameMatchedOut(BaseModel):
    id: Optional[str] = None
    matchStatus: Optional[MatchStatus] = Field(
        None, description='The name matching status.'
    )
    score: Optional[float] = None
    script: Optional[str] = None


class PersonalNameCastegroupOut(BaseModel):
    castegroup: Optional[str] = Field(None, description='Most likely caste group')
    castegroupAlt: Optional[str] = Field(
        None, description='Second best alternative : caste group '
    )
    castegroupTop: Optional[List[str]] = Field(
        None, description='List caste group (top 10)'
    )
    id: Optional[str] = None
    name: Optional[str] = Field(None, description='The input name.')
    probabilityAltCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for country OR countryAlt to have been guessed correctly. -1 = still calibrating. ',
    )
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for country to have been guessed correctly. -1 = still calibrating. ',
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class PersonalNameGenderedOut(BaseModel):
    genderScale: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None, description='Compatibility to NamSor_v1 Gender Scale M[-1..U..+1]F value.'
    )
    id: Optional[str] = None
    likelyGender: Optional[LikelyGender] = Field(None, description='Most likely gender')
    name: Optional[str] = Field(None, description='The input name')
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for inferred gender to have been guessed correctly. -1 = still calibrating. ',
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Compatibility to NamSor_v1 Gender score value. Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class PersonalNameGeoIn(BaseModel):
    countryIso2: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None


class PersonalNameGeoOut(BaseModel):
    countriesTop: Optional[List[str]] = Field(
        None, description='List countries (top 10)'
    )
    country: Optional[str] = Field(None, description='Most likely country ')
    countryAlt: Optional[str] = Field(
        None, description='Second best alternative : country '
    )
    id: Optional[str] = None
    name: Optional[str] = Field(None, description='The input name.')
    probabilityAltCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for country OR countryAlt to have been guessed correctly. -1 = still calibrating. ',
    )
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for country to have been guessed correctly. -1 = still calibrating. ',
    )
    region: Optional[str] = Field(
        None, description='Most likely region (based on country ISO2 code)'
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None
    subRegion: Optional[str] = Field(
        None, description='Most likely sub region (based on country ISO2 code)'
    )
    topRegion: Optional[str] = Field(
        None, description='Most likely top region (based on country ISO2 code)'
    )


class PersonalNameGeoSubdivisionIn(BaseModel):
    countryIso2: Optional[str] = None
    id: Optional[str] = None
    name: Optional[str] = None
    subdivisionIso: Optional[str] = None


class PersonalNameIn(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None


class NameParserType(Enum):
    FN1LN1 = 'FN1LN1'
    LN1FN1 = 'LN1FN1'
    FN1LN2 = 'FN1LN2'
    LN2FN1 = 'LN2FN1'
    FN1LNx = 'FN1LNx'
    LNxFN1 = 'LNxFN1'
    FN2LN1 = 'FN2LN1'
    LN1FN2 = 'LN1FN2'
    FN2LN2 = 'FN2LN2'
    LN2FN2 = 'LN2FN2'
    FN2LNx = 'FN2LNx'
    LNxFN2 = 'LNxFN2'
    FNxLN1 = 'FNxLN1'
    LN1FNx = 'LN1FNx'
    FNxLN2 = 'FNxLN2'
    LN2FNx = 'LN2FNx'
    FNxLNx = 'FNxLNx'
    LNxFNx = 'LNxFNx'


class NameParserTypeAlt(Enum):
    FN1LN1 = 'FN1LN1'
    LN1FN1 = 'LN1FN1'
    FN1LN2 = 'FN1LN2'
    LN2FN1 = 'LN2FN1'
    FN1LNx = 'FN1LNx'
    LNxFN1 = 'LNxFN1'
    FN2LN1 = 'FN2LN1'
    LN1FN2 = 'LN1FN2'
    FN2LN2 = 'FN2LN2'
    LN2FN2 = 'LN2FN2'
    FN2LNx = 'FN2LNx'
    LNxFN2 = 'LNxFN2'
    FNxLN1 = 'FNxLN1'
    LN1FNx = 'LN1FNx'
    FNxLN2 = 'FNxLN2'
    LN2FNx = 'LN2FNx'
    FNxLNx = 'FNxLNx'
    LNxFNx = 'LNxFNx'


class PersonalNameParsedOut(BaseModel):
    firstLastName: Optional[FirstLastNameOut] = None
    id: Optional[str] = None
    name: Optional[str] = Field(None, description='The input name')
    nameParserType: Optional[NameParserType] = Field(
        None,
        description='Name parsing is addressed as a classification problem, for example FN1LN1 means a first then last name order.',
    )
    nameParserTypeAlt: Optional[NameParserTypeAlt] = Field(
        None,
        description='Second best alternative parsing. Name parsing is addressed as a classification problem, for example FN1LN1 means a first then last name order.',
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class PersonalNameReligionedOut(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = Field(None, description='The input name.')
    probabilityAltCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for country OR countryAlt to have been guessed correctly. -1 = still calibrating. ',
    )
    probabilityCalibrated: Optional[confloat(ge=-1.0, le=1.0)] = Field(
        None,
        description='The calibrated probability for country to have been guessed correctly. -1 = still calibrating. ',
    )
    religion: Optional[str] = Field(None, description='Most likely religion')
    religionAlt: Optional[str] = Field(
        None, description='Second best alternative : religion '
    )
    religionsTop: Optional[List[str]] = Field(
        None, description='List countries (top 10)'
    )
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class PersonalNameSubdivisionIn(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    subdivisionIso: Optional[str] = None


class ProperNounCategorizedOut(BaseModel):
    commonType: Optional[str] = Field(
        None, description='The most likely common name type'
    )
    commonTypeAlt: Optional[str] = Field(
        None, description='Best alternative for : The most likely common name type'
    )
    id: Optional[str] = None
    name: Optional[str] = Field(None, description='The input name')
    score: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None,
        description='Higher score is better, but score is not normalized. Use calibratedProbability if available. ',
    )
    script: Optional[str] = None


class RegionISO(BaseModel):
    countryFIPS: Optional[str] = None
    countryISO2: Optional[str] = None
    countryISO3: Optional[str] = None
    countryName: Optional[str] = None
    countryNumCode: Optional[str] = None
    region: Optional[str] = None
    subregion: Optional[str] = None
    topregion: Optional[str] = None


class RegionOut(BaseModel):
    countriesAndRegions: Optional[List[RegionISO]] = Field(
        None, description='List of countries and regions'
    )


class SoftwareVersionOut(BaseModel):
    softwareNameAndVersion: Optional[str] = Field(
        None, description='The software version'
    )
    softwareVersion: Optional[List[int]] = Field(
        None, description='The software version major minor build'
    )


class APIClassifiersStatusOut(BaseModel):
    classifiers: Optional[List[APIClassifierOut]] = Field(
        None, description='The list of classifiers and versions.'
    )
    softwareVersion: Optional[SoftwareVersionOut] = None


class APICounterV2Out(BaseModel):
    apiKey: Optional[APIKeyOut] = None
    apiService: Optional[str] = Field(
        None, description='The apiService corresponds to the classifier name.'
    )
    createdDateTime: Optional[int] = Field(
        None, description='The create datetime of the counter.'
    )
    hostAddress: Optional[str] = Field(None, description='The processing hostAddress.')
    lastFlushedDateTime: Optional[int] = Field(
        None, description='The flush datetime of the counter.'
    )
    lastUsedDateTime: Optional[int] = Field(
        None, description='The last usage datetime of the counter.'
    )
    serviceFeaturesUsage: Optional[Dict[str, int]] = Field(
        None, description='Usage of special features, such as Chinese, Japanese.'
    )
    totalUsage: Optional[int] = Field(None, description='The usage of the counter.')


class APIPeriodUsageOut(BaseModel):
    billingPeriod: Optional[APIBillingPeriodUsageOut] = None
    overageCurrency: Optional[str] = Field(
        None, description='Currency of the overage amount.'
    )
    overageExclTax: Optional[float] = Field(
        None, description='Overage amount including any tax.'
    )
    overageInclTax: Optional[float] = Field(
        None, description='Overage amount including tax (if applicable).'
    )
    overageQuantity: Optional[int] = Field(
        None,
        description='Quantity above monthly quota of the current subscritpion, in units.',
    )
    subscription: Optional[APIPlanSubscriptionOut] = None


class APIUsageHistoryOut(BaseModel):
    detailedUsage: Optional[List[APICounterV2Out]] = Field(
        None, description='Detailed usage as reported by the deduplicating API counter.'
    )


class BatchFirstLastNameDiasporaedOut(BaseModel):
    personalNames: Optional[List[FirstLastNameDiasporaedOut]] = Field(
        None, description='Classified diaspora names'
    )


class BatchFirstLastNameGenderIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[FirstLastNameGenderIn]] = None


class BatchFirstLastNameGenderedOut(BaseModel):
    personalNames: Optional[List[FirstLastNameGenderedOut]] = Field(
        None, description='Classified genderized names'
    )


class BatchFirstLastNameGeoIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[FirstLastNameGeoIn]] = None


class BatchFirstLastNameGeoSubclassificationOut(BaseModel):
    personalNames: Optional[List[FirstLastNameGeoSubclassificationOut]] = Field(
        None, description='Classified names at sub country level (region or state)'
    )


class BatchFirstLastNameGeoZippedIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[FirstLastNameGeoZippedIn]] = None


class BatchFirstLastNameIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[FirstLastNameIn]] = None


class BatchFirstLastNameOriginedOut(BaseModel):
    personalNames: Optional[List[FirstLastNameOriginedOut]] = Field(
        None, description='Classified origined names'
    )


class BatchFirstLastNamePhoneCodedOut(BaseModel):
    personalNamesWithPhoneNumbers: Optional[List[FirstLastNamePhoneCodedOut]] = Field(
        None, description='Classified phone-coded names'
    )


class BatchFirstLastNamePhoneNumberGeoIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNamesWithPhoneNumbers: Optional[List[FirstLastNamePhoneNumberGeoIn]] = None


class BatchFirstLastNamePhoneNumberIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNamesWithPhoneNumbers: Optional[List[FirstLastNamePhoneNumberIn]] = None


class BatchFirstLastNameUSRaceEthnicityOut(BaseModel):
    personalNames: Optional[List[FirstLastNameUSRaceEthnicityOut]] = Field(
        None, description="Classified US 'race'/ethnicized names"
    )


class BatchNameGeoIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    properNouns: Optional[List[NameGeoIn]] = None


class BatchNameIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    properNouns: Optional[List[NameIn]] = None


class BatchNameMatchCandidatesOut(BaseModel):
    namesAndMatchCandidates: Optional[List[NameMatchCandidatesOut]] = Field(
        None, description='Classified matched names'
    )


class BatchNameMatchedOut(BaseModel):
    matchedNames: Optional[List[NameMatchedOut]] = Field(
        None, description='Classified matched names'
    )


class BatchPersonalNameCastegroupOut(BaseModel):
    personalNames: Optional[List[PersonalNameCastegroupOut]] = Field(
        None, description='Caste group-coded names'
    )


class BatchPersonalNameGenderedOut(BaseModel):
    personalNames: Optional[List[PersonalNameGenderedOut]] = Field(
        None, description='Classified genderized names'
    )


class BatchPersonalNameGeoIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[PersonalNameGeoIn]] = None


class BatchPersonalNameGeoOut(BaseModel):
    personalNames: Optional[List[PersonalNameGeoOut]] = Field(
        None, description='Classified geo names'
    )


class BatchPersonalNameGeoSubdivisionIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[PersonalNameGeoSubdivisionIn]] = None


class BatchPersonalNameIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[PersonalNameIn]] = None


class BatchPersonalNameParsedOut(BaseModel):
    personalNames: Optional[List[PersonalNameParsedOut]] = Field(
        None, description='Classified parsed names'
    )


class BatchPersonalNameReligionedOut(BaseModel):
    personalNames: Optional[List[PersonalNameReligionedOut]] = Field(
        None, description='religious-coded names'
    )


class BatchPersonalNameSubdivisionIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[PersonalNameSubdivisionIn]] = None


class BatchProperNounCategorizedOut(BaseModel):
    properNouns: Optional[List[ProperNounCategorizedOut]] = Field(
        None, description='Classified typed proper names'
    )


class CorridorIn(BaseModel):
    firstLastNameGeoFrom: Optional[FirstLastNameGeoIn] = None
    firstLastNameGeoTo: Optional[FirstLastNameGeoIn] = None
    id: Optional[str] = None


class CorridorOut(BaseModel):
    FirstLastNameDiasporaedOut_1: Optional[FirstLastNameDiasporaedOut] = Field(
        None, alias='FirstLastNameDiasporaedOut'
    )
    FirstLastNameGenderedOut_1: Optional[FirstLastNameGenderedOut] = Field(
        None, alias='FirstLastNameGenderedOut'
    )
    FirstLastNameOriginedOut_1: Optional[FirstLastNameOriginedOut] = Field(
        None, alias='FirstLastNameOriginedOut'
    )
    id: Optional[str] = None
    script: Optional[str] = None


class MatchPersonalFirstLastNameIn(BaseModel):
    id: Optional[str] = None
    name1: Optional[FirstLastNameIn] = None
    name2: Optional[PersonalNameIn] = None


class BatchCorridorIn(BaseModel):
    corridorFromTo: Optional[List[CorridorIn]] = None
    facts: Optional[List[FactIn]] = None


class BatchCorridorOut(BaseModel):
    corridorFromTo: Optional[List[CorridorOut]] = Field(
        None, description='Classified corridors'
    )


class BatchMatchPersonalFirstLastNameIn(BaseModel):
    facts: Optional[List[FactIn]] = None
    personalNames: Optional[List[MatchPersonalFirstLastNameIn]] = None
